# coding: utf-8

"""
    COTOHA API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class DetectMisrecognitionCandidatesCorrection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'form': 'str',
        'correct_score': 'float'
    }

    attribute_map = {
        'form': 'form',
        'correct_score': 'correct_score'
    }

    def __init__(self, form=None, correct_score=None):  # noqa: E501
        """DetectMisrecognitionCandidatesCorrection - a model defined in Swagger"""  # noqa: E501
        self._form = None
        self._correct_score = None
        self.discriminator = None
        if form is not None:
            self.form = form
        if correct_score is not None:
            self.correct_score = correct_score

    @property
    def form(self):
        """Gets the form of this DetectMisrecognitionCandidatesCorrection.  # noqa: E501


        :return: The form of this DetectMisrecognitionCandidatesCorrection.  # noqa: E501
        :rtype: str
        """
        return self._form

    @form.setter
    def form(self, form):
        """Sets the form of this DetectMisrecognitionCandidatesCorrection.


        :param form: The form of this DetectMisrecognitionCandidatesCorrection.  # noqa: E501
        :type: str
        """

        self._form = form

    @property
    def correct_score(self):
        """Gets the correct_score of this DetectMisrecognitionCandidatesCorrection.  # noqa: E501


        :return: The correct_score of this DetectMisrecognitionCandidatesCorrection.  # noqa: E501
        :rtype: float
        """
        return self._correct_score

    @correct_score.setter
    def correct_score(self, correct_score):
        """Sets the correct_score of this DetectMisrecognitionCandidatesCorrection.


        :param correct_score: The correct_score of this DetectMisrecognitionCandidatesCorrection.  # noqa: E501
        :type: float
        """

        self._correct_score = correct_score

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DetectMisrecognitionCandidatesCorrection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DetectMisrecognitionCandidatesCorrection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
