# coding: utf-8

"""
    COTOHA API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class DetectMisrecognitionCandidates(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'begin_pos': 'int',
        'end_pos': 'int',
        'form': 'str',
        'detect_score': 'float',
        'correction': 'list[DetectMisrecognitionCandidatesCorrection]'
    }

    attribute_map = {
        'begin_pos': 'begin_pos',
        'end_pos': 'end_pos',
        'form': 'form',
        'detect_score': 'detect_score',
        'correction': 'correction'
    }

    def __init__(self, begin_pos=None, end_pos=None, form=None, detect_score=None, correction=None):  # noqa: E501
        """DetectMisrecognitionCandidates - a model defined in Swagger"""  # noqa: E501
        self._begin_pos = None
        self._end_pos = None
        self._form = None
        self._detect_score = None
        self._correction = None
        self.discriminator = None
        if begin_pos is not None:
            self.begin_pos = begin_pos
        if end_pos is not None:
            self.end_pos = end_pos
        if form is not None:
            self.form = form
        if detect_score is not None:
            self.detect_score = detect_score
        if correction is not None:
            self.correction = correction

    @property
    def begin_pos(self):
        """Gets the begin_pos of this DetectMisrecognitionCandidates.  # noqa: E501


        :return: The begin_pos of this DetectMisrecognitionCandidates.  # noqa: E501
        :rtype: int
        """
        return self._begin_pos

    @begin_pos.setter
    def begin_pos(self, begin_pos):
        """Sets the begin_pos of this DetectMisrecognitionCandidates.


        :param begin_pos: The begin_pos of this DetectMisrecognitionCandidates.  # noqa: E501
        :type: int
        """

        self._begin_pos = begin_pos

    @property
    def end_pos(self):
        """Gets the end_pos of this DetectMisrecognitionCandidates.  # noqa: E501


        :return: The end_pos of this DetectMisrecognitionCandidates.  # noqa: E501
        :rtype: int
        """
        return self._end_pos

    @end_pos.setter
    def end_pos(self, end_pos):
        """Sets the end_pos of this DetectMisrecognitionCandidates.


        :param end_pos: The end_pos of this DetectMisrecognitionCandidates.  # noqa: E501
        :type: int
        """

        self._end_pos = end_pos

    @property
    def form(self):
        """Gets the form of this DetectMisrecognitionCandidates.  # noqa: E501


        :return: The form of this DetectMisrecognitionCandidates.  # noqa: E501
        :rtype: str
        """
        return self._form

    @form.setter
    def form(self, form):
        """Sets the form of this DetectMisrecognitionCandidates.


        :param form: The form of this DetectMisrecognitionCandidates.  # noqa: E501
        :type: str
        """

        self._form = form

    @property
    def detect_score(self):
        """Gets the detect_score of this DetectMisrecognitionCandidates.  # noqa: E501


        :return: The detect_score of this DetectMisrecognitionCandidates.  # noqa: E501
        :rtype: float
        """
        return self._detect_score

    @detect_score.setter
    def detect_score(self, detect_score):
        """Sets the detect_score of this DetectMisrecognitionCandidates.


        :param detect_score: The detect_score of this DetectMisrecognitionCandidates.  # noqa: E501
        :type: float
        """

        self._detect_score = detect_score

    @property
    def correction(self):
        """Gets the correction of this DetectMisrecognitionCandidates.  # noqa: E501


        :return: The correction of this DetectMisrecognitionCandidates.  # noqa: E501
        :rtype: list[DetectMisrecognitionCandidatesCorrection]
        """
        return self._correction

    @correction.setter
    def correction(self, correction):
        """Sets the correction of this DetectMisrecognitionCandidates.


        :param correction: The correction of this DetectMisrecognitionCandidates.  # noqa: E501
        :type: list[DetectMisrecognitionCandidatesCorrection]
        """

        self._correction = correction

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DetectMisrecognitionCandidates, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DetectMisrecognitionCandidates):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
