# coding: utf-8

"""
    COTOHA API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Ne(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sentence': 'str',
        'type': 'str',
        'dic_type': 'list[str]'
    }

    attribute_map = {
        'sentence': 'sentence',
        'type': 'type',
        'dic_type': 'dic_type'
    }

    def __init__(self, sentence=None, type='default', dic_type=None):  # noqa: E501
        """Ne - a model defined in Swagger"""  # noqa: E501
        self._sentence = None
        self._type = None
        self._dic_type = None
        self.discriminator = None
        self.sentence = sentence
        if type is not None:
            self.type = type
        if dic_type is not None:
            self.dic_type = dic_type

    @property
    def sentence(self):
        """Gets the sentence of this Ne.  # noqa: E501


        :return: The sentence of this Ne.  # noqa: E501
        :rtype: str
        """
        return self._sentence

    @sentence.setter
    def sentence(self, sentence):
        """Sets the sentence of this Ne.


        :param sentence: The sentence of this Ne.  # noqa: E501
        :type: str
        """
        if sentence is None:
            raise ValueError("Invalid value for `sentence`, must not be `None`")  # noqa: E501

        self._sentence = sentence

    @property
    def type(self):
        """Gets the type of this Ne.  # noqa: E501


        :return: The type of this Ne.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Ne.


        :param type: The type of this Ne.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def dic_type(self):
        """Gets the dic_type of this Ne.  # noqa: E501


        :return: The dic_type of this Ne.  # noqa: E501
        :rtype: list[str]
        """
        return self._dic_type

    @dic_type.setter
    def dic_type(self, dic_type):
        """Sets the dic_type of this Ne.


        :param dic_type: The dic_type of this Ne.  # noqa: E501
        :type: list[str]
        """

        self._dic_type = dic_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Ne, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Ne):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
