# coding: utf-8

"""
    COTOHA API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ParseInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tokens': 'list[TokenInfo]',
        'chunk_info': 'ChunkInfo'
    }

    attribute_map = {
        'tokens': 'tokens',
        'chunk_info': 'chunk_info'
    }

    def __init__(self, tokens=None, chunk_info=None):  # noqa: E501
        """ParseInfo - a model defined in Swagger"""  # noqa: E501
        self._tokens = None
        self._chunk_info = None
        self.discriminator = None
        if tokens is not None:
            self.tokens = tokens
        if chunk_info is not None:
            self.chunk_info = chunk_info

    @property
    def tokens(self):
        """Gets the tokens of this ParseInfo.  # noqa: E501


        :return: The tokens of this ParseInfo.  # noqa: E501
        :rtype: list[TokenInfo]
        """
        return self._tokens

    @tokens.setter
    def tokens(self, tokens):
        """Sets the tokens of this ParseInfo.


        :param tokens: The tokens of this ParseInfo.  # noqa: E501
        :type: list[TokenInfo]
        """

        self._tokens = tokens

    @property
    def chunk_info(self):
        """Gets the chunk_info of this ParseInfo.  # noqa: E501


        :return: The chunk_info of this ParseInfo.  # noqa: E501
        :rtype: ChunkInfo
        """
        return self._chunk_info

    @chunk_info.setter
    def chunk_info(self, chunk_info):
        """Sets the chunk_info of this ParseInfo.


        :param chunk_info: The chunk_info of this ParseInfo.  # noqa: E501
        :type: ChunkInfo
        """

        self._chunk_info = chunk_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ParseInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ParseInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
