# coding: utf-8

"""
    COTOHA API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class RemoveFillerInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fillers': 'list[RemoveFillerInfoFillers]',
        'normalized_sentence': 'str',
        'fixed_sentence': 'str'
    }

    attribute_map = {
        'fillers': 'fillers',
        'normalized_sentence': 'normalized_sentence',
        'fixed_sentence': 'fixed_sentence'
    }

    def __init__(self, fillers=None, normalized_sentence=None, fixed_sentence=None):  # noqa: E501
        """RemoveFillerInfo - a model defined in Swagger"""  # noqa: E501
        self._fillers = None
        self._normalized_sentence = None
        self._fixed_sentence = None
        self.discriminator = None
        if fillers is not None:
            self.fillers = fillers
        if normalized_sentence is not None:
            self.normalized_sentence = normalized_sentence
        if fixed_sentence is not None:
            self.fixed_sentence = fixed_sentence

    @property
    def fillers(self):
        """Gets the fillers of this RemoveFillerInfo.  # noqa: E501


        :return: The fillers of this RemoveFillerInfo.  # noqa: E501
        :rtype: list[RemoveFillerInfoFillers]
        """
        return self._fillers

    @fillers.setter
    def fillers(self, fillers):
        """Sets the fillers of this RemoveFillerInfo.


        :param fillers: The fillers of this RemoveFillerInfo.  # noqa: E501
        :type: list[RemoveFillerInfoFillers]
        """

        self._fillers = fillers

    @property
    def normalized_sentence(self):
        """Gets the normalized_sentence of this RemoveFillerInfo.  # noqa: E501


        :return: The normalized_sentence of this RemoveFillerInfo.  # noqa: E501
        :rtype: str
        """
        return self._normalized_sentence

    @normalized_sentence.setter
    def normalized_sentence(self, normalized_sentence):
        """Sets the normalized_sentence of this RemoveFillerInfo.


        :param normalized_sentence: The normalized_sentence of this RemoveFillerInfo.  # noqa: E501
        :type: str
        """

        self._normalized_sentence = normalized_sentence

    @property
    def fixed_sentence(self):
        """Gets the fixed_sentence of this RemoveFillerInfo.  # noqa: E501


        :return: The fixed_sentence of this RemoveFillerInfo.  # noqa: E501
        :rtype: str
        """
        return self._fixed_sentence

    @fixed_sentence.setter
    def fixed_sentence(self, fixed_sentence):
        """Sets the fixed_sentence of this RemoveFillerInfo.


        :param fixed_sentence: The fixed_sentence of this RemoveFillerInfo.  # noqa: E501
        :type: str
        """

        self._fixed_sentence = fixed_sentence

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RemoveFillerInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RemoveFillerInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
