# coding: utf-8

"""
    COTOHA API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Summary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'document': 'str',
        'sent_len': 'int'
    }

    attribute_map = {
        'document': 'document',
        'sent_len': 'sent_len'
    }

    def __init__(self, document=None, sent_len=None):  # noqa: E501
        """Summary - a model defined in Swagger"""  # noqa: E501
        self._document = None
        self._sent_len = None
        self.discriminator = None
        self.document = document
        if sent_len is not None:
            self.sent_len = sent_len

    @property
    def document(self):
        """Gets the document of this Summary.  # noqa: E501


        :return: The document of this Summary.  # noqa: E501
        :rtype: str
        """
        return self._document

    @document.setter
    def document(self, document):
        """Sets the document of this Summary.


        :param document: The document of this Summary.  # noqa: E501
        :type: str
        """
        if document is None:
            raise ValueError("Invalid value for `document`, must not be `None`")  # noqa: E501

        self._document = document

    @property
    def sent_len(self):
        """Gets the sent_len of this Summary.  # noqa: E501


        :return: The sent_len of this Summary.  # noqa: E501
        :rtype: int
        """
        return self._sent_len

    @sent_len.setter
    def sent_len(self, sent_len):
        """Sets the sent_len of this Summary.


        :param sent_len: The sent_len of this Summary.  # noqa: E501
        :type: int
        """

        self._sent_len = sent_len

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Summary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Summary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
