# coding: utf-8

"""
    COTOHA API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_dev_nlp_beta_detect_misrecognition_post(self):
        """Test case for api_dev_nlp_beta_detect_misrecognition_post

        """
        pass

    def test_api_dev_nlp_beta_remove_filler_post(self):
        """Test case for api_dev_nlp_beta_remove_filler_post

        """
        pass

    def test_api_dev_nlp_beta_user_attribute_post(self):
        """Test case for api_dev_nlp_beta_user_attribute_post

        """
        pass

    def test_api_dev_nlp_v1_coreference_post(self):
        """Test case for api_dev_nlp_v1_coreference_post

        """
        pass

    def test_api_dev_nlp_v1_keyword_post(self):
        """Test case for api_dev_nlp_v1_keyword_post

        """
        pass

    def test_api_dev_nlp_v1_ne_post(self):
        """Test case for api_dev_nlp_v1_ne_post

        """
        pass

    def test_api_dev_nlp_v1_parse_post(self):
        """Test case for api_dev_nlp_v1_parse_post

        """
        pass

    def test_api_dev_nlp_v1_sentence_type_post(self):
        """Test case for api_dev_nlp_v1_sentence_type_post

        """
        pass

    def test_api_dev_nlp_v1_sentiment_post(self):
        """Test case for api_dev_nlp_v1_sentiment_post

        """
        pass

    def test_api_dev_nlp_v1_similarity_post(self):
        """Test case for api_dev_nlp_v1_similarity_post

        """
        pass

    def test_v1_oauth_accesstokens_post(self):
        """Test case for v1_oauth_accesstokens_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
