# coding: utf-8

"""
    COTOHA API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.ne_info import NeInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestNeInfo(unittest.TestCase):
    """NeInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNeInfo(self):
        """Test NeInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ne_info.NeInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
