# coding: utf-8

"""
    COTOHA API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.dialog_act import DialogAct  # noqa: E501
from swagger_client.rest import ApiException


class TestDialogAct(unittest.TestCase):
    """DialogAct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDialogAct(self):
        """Test DialogAct"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.dialog_act.DialogAct()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
