# coding: utf-8

"""
    COTOHA API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.detect_misrecognition_info_candidates import DetectMisrecognitionInfoCandidates  # noqa: E501
from swagger_client.rest import ApiException


class TestDetectMisrecognitionInfoCandidates(unittest.TestCase):
    """DetectMisrecognitionInfoCandidates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetectMisrecognitionInfoCandidates(self):
        """Test DetectMisrecognitionInfoCandidates"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.detect_misrecognition_info_candidates.DetectMisrecognitionInfoCandidates()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
