# coding: utf-8

"""
    COTOHA API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.parse import Parse  # noqa: E501
from swagger_client.rest import ApiException


class TestParse(unittest.TestCase):
    """Parse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParse(self):
        """Test Parse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.parse.Parse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
