# coding: utf-8

"""
    COTOHA API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.referent import Referent  # noqa: E501
from swagger_client.rest import ApiException


class TestReferent(unittest.TestCase):
    """Referent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReferent(self):
        """Test Referent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.referent.Referent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
