# coding: utf-8

"""
    COTOHA API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.remove_filler_info import RemoveFillerInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestRemoveFillerInfo(unittest.TestCase):
    """RemoveFillerInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemoveFillerInfo(self):
        """Test RemoveFillerInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.remove_filler_info.RemoveFillerInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
