# coding: utf-8

"""
    COTOHA API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.user_attribute import UserAttribute  # noqa: E501
from swagger_client.rest import ApiException


class TestUserAttribute(unittest.TestCase):
    """UserAttribute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserAttribute(self):
        """Test UserAttribute"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_attribute.UserAttribute()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
