# coding: utf-8

"""
    COTOHA API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.referents import Referents  # noqa: E501
from swagger_client.rest import ApiException


class TestReferents(unittest.TestCase):
    """Referents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReferents(self):
        """Test Referents"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.referents.Referents()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
